name: user_repository
description: Dart package which manages user domain

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.2.4
  equatable: ^1.2.5
  entity:
    path: ../entity
