name: genproto
description: Generated gRPC clients for the api

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  protobuf: ^1.1.0
  grpc: ^2.8.0
